### ISSUE TITLE
homework submission language edits

### ISSUE THREAD

**Issue by mistrm82** [hbctraining/Intro-to-shell-flipped#10]
Do not provide a text file for them to fill in, it is confusing.

Instead just ask them to submit the answer to each Exercise in the lessons. Explicitly state in bold that we do not want a dump of the terminal. Only the final line of the code that answers the question

**Comment by mistrm82** [comment]
think about having a survey for homework question submission

**Comment by rkhetani** [comment]
Add a note about not pasting everything from their terminal.

**Comment by rkhetani** [comment]
updated schedule page
