### ISSUE TITLE
Broken link to data for exercises

### ISSUE THREAD

**Issue by kalavattam** [hbctraining/Intro-to-shell-flipped#29]
Hi all,

Thanks for the great training resources. I am having some students work through them (self-learning).

We noticed that the link to the data for the exercises, [https://www.dropbox.com/s/3lua2h1oo18gbug/unix_lesson.tar.gz?dl=1](https://www.dropbox.com/s/3lua2h1oo18gbug/unix_lesson.tar.gz?dl=1), is broken and just wanted to inform you of that.

I think I found the same data file hosted as part of another hbctraining course ([https://github.com/hbctraining/Training-modules/blob/master/Intro_shell/data/unix_lesson.zip?raw=true](https://github.com/hbctraining/Training-modules/blob/master/Intro_shell/data/unix_lesson.zip?raw=true)) and am having the students use that file for now.

Thanks,
Kris

**Comment by rkhetani** [comment]
@kalavattam Thank you!

We will update the link in this repository.

Best,
Radhika
