### ISSUE TITLE
Add ctrl + c command?

### ISSUE THREAD

**Issue by jihe-liu** [hbctraining/Intro-to-shell-flipped#5]
Introduce Ctrl + c command in the lesson?

**Comment by mistrm82** [comment]
This is at the end of https://github.com/hbctraining/Intro-to-shell-flipped/blob/master/lessons/02_wildcards_shortcuts.md

Maybe we should move it up to be in the in-class intro lesson?

**Comment by jihe-liu** [comment]
I added some blurb for ctrl+c in the lesson. I don't find it absolutely necessary to move up to in-class, since we already have quite a few to cover in-class. The same goes for tab completion. We could see how students pick up these concepts as self-learning.
